---
- name: using loops to get the username
  hosts: localhost
  vars:
    users: 
       - user1
       - user2
       - user3
       - user4
       - user5
       - user6
       - user7
       - user8
       - user9
       - user10
  tasks:
    - name: print the users
      debug:
        msg: "{{ item }}"
      with_items: "{{ users }}"
    
